### PR TITLE
Use ruamel.yaml again for dataplusmeta.

### PR DESCRIPTION
**Pull request by adriesse**

### CODE REVIEW

**Comment by adriesse** [comment]
@echedey-ls Did I do this right with the requirements?

**Comment by echedey-ls** [comment]
> @echedey-ls Did I do this right with the requirements?

Yes, I'm surprised by how easy it seems to revert back to it! I should have made some error while looking into the compatible pythons... 😬

**Comment by echedey-ls** [comment]
Well, one file needs updating still, `pyproject.toml` has a section for dependencies. Pin to minimal version or greater (`ruamel.yaml>=0.15` or whatever fits well) and remove the old dependency `PyYAML`. I will have a look into whether or not maybe the CI requirements files are really necessary, maybe we can get rid of them unless we publish to conda-forge.

**Comment by adriesse** [comment]
> I will have a look into whether or not maybe the CI requirements files are really necessary, maybe we can get rid of them unless we publish to conda-forge.

Ok, I'll this PR pause here.

**Comment by echedey-ls** [comment]
> Ok, I'll this PR pause here.

Don't worry about that. In fact, now I remember that I did include a system similar but not equal to that one of pvlib. It makes a lot of sense to test the minimal versions and that can only be achieved via these files. They can merged into two files, one for minimal and another one for latest versions, but I think it's clearer as is.

For what this PR tries to achieve, one last change would be needed: remove all PyYAML references in `pyproject.toml`, `ci/requirements*.txt` and wherever else without leaving a single trace.

**Comment by echedey-ls** [comment]
For the purpose of this PR, LGTM. I will make a last PR for cleaning up things and making maintenance less difficult in the future.

**Review by echedey-ls — APPROVED** [review]

**Pull request merged**
