### PR TITLE
[CI/MAINT]: Tidy CI files and uncompatible dependencies versions

### PR DESCRIPTION
**Pull request by echedey-ls**
- Removed usual pip requirements that were not really necessary to specify the versions to tests against (a maintenance burden, I did not think about making the install requirements step optional at first)
- Kept & updated minimal versions to use exact version matching (better than `~=`)
- Updated the `pyproject.toml` dependencies versions to match what really is compatible after recent changes and on the lowest supported version.
- Pinned docs dependencies to minor versions to avoid unexpected changes in the future, now that RTD is finally set up.

### CODE REVIEW

**Comment by echedey-ls** [comment]
Merge after #13

**Comment by adriesse** [comment]
@echedey-ls Could you include the tests in the distribution package while you're at it?

**Comment by echedey-ls** [comment]
@adriesse do you mean shipping them in the wheel too? They already are in the source distribution.

**Comment by echedey-ls** [comment]
> @echedey-ls Could you include the tests in the distribution package while you're at it?

I've created #16 for that, so you can decide on it and atomically revert that change if you want in the future.

**Pull request merged**
